name: main
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      # Install app1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: app1
      - name: App1 tests
        run: npm t
        working-directory: app1
